### ISSUE TITLE
Error while compiling Numba-DPPY from source on JLSE

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dppy#261] opened 2021-02-18 16:08 UTC
Building Numba-DPPY on JLSE throws an error when compiling the atomics operations.

Build command:
```
python setup.py develop
```

Error:
```
Finished processing dependencies for numba-dppy==0.12.0+19.gb3eff86
Incompatible epoch: Bitcode '16777216' vs current: '0'
Traceback (most recent call last):
  File "setup.py", line 172, in <module>
    setup(**metadata)
  File "/home/adarshyoga/.conda/envs/dppy_dev_env/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/adarshyoga/.conda/envs/dppy_dev_env/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/adarshyoga/.conda/envs/dppy_dev_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/adarshyoga/.conda/envs/dppy_dev_env/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 86, in run
    spirv_compile()
  File "setup.py", line 129, in spirv_compile
    subprocess.check_call(spirv_args, stderr=subprocess.STDOUT, shell=False)
  File "/home/adarshyoga/.conda/envs/dppy_dev_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['llvm-spirv', '-o', 'numba_dppy/ocl/atomics/atomic_ops.spir', 'numba_dppy/ocl/atomics/atomic_ops.bc']' returned non-zero exit status 1.
```

**Comment by PokhodenkoSA** [comment] 2021-03-16 05:41
@adarshyoga Did you source onAPI compiler environment?
```bash
source /opt/intel/oneapi/compiler/latest/env/vars.sh
```

**Comment by adarshyoga** [comment] 2021-03-16 23:04
Yes, I am trying this on Argonne's JLSE systems. The compiler env variables are all correctly setup. Even ONEAPI_ROOT points to the correct directory.

**Comment by diptorupd** [comment] 2021-05-27 04:58
@adarshyoga I believe the issue is now resolved and does not replicate with latest oneAPI and numba-dppy. I am closing the issue, please reopen if you encounter the issue again.

**Closed by diptorupd** 2021-05-27 04:58 UTC
Labels: bug, build
