### ISSUE TITLE
Undelcared variable

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#461] opened 2021-06-17 19:30 UTC
https://github.com/IntelPython/numba-dppy/blob/c1b3a89e2806005938dfd11f97f496f7bd427fe9/numba_dppy/dppy_parfor_diagnostics.py#L99

Where is the fadj variable coming from? @PokhodenkoSA @1e-to

**Comment by PokhodenkoSA** [comment] 2021-06-18 07:46
Duplicate of https://github.com/IntelPython/numba-dppy/issues/312.

**Closed** 2021-06-22 12:34 UTC
