### ISSUE TITLE
Move numba_dppy unit tests out of numba_dppy/tests/dppl to numba_dppy/tests

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/numba-dppy#23] opened 2020-11-23 21:53 UTC
We do not need the extra dppl directory iniside numba_dppy/tests (https://github.com/IntelPython/numba-dppy/tree/main/numba_dppy/tests). Let us move all the tests inside numba_dppy/tests.

**Comment by PokhodenkoSA** [comment] 2020-11-24 08:00
Should be closed by https://github.com/IntelPython/numba/pull/111

**Comment by 96RadhikaJadhav** [comment] 2020-11-28 15:29
@PokhodenkoSA/@reazulhoque  Does this mean just removing the dppl folder inside numba_dppy/tests and no other code changes? 
If so, then could you please assign this issue to me so I can create a PR.

**Comment by PokhodenkoSA** [comment] 2020-11-29 22:27
Hi @96RadhikaJadhav. @reazulhoque mean that we need to eliminate nested folder dppl, so all tests inside it should go to tests folder. You can propose your pull request. I would like to know if you will have some problems with running tests after that. If you will, please, write here.
Thank you for your interest.

**Comment by 96RadhikaJadhav** [comment] 2020-11-30 06:39
@PokhodenkoSA  I have created a PR. Could you please review it?

**Comment by PokhodenkoSA** [comment] 2020-11-30 12:06
@96RadhikaJadhav possibly I have explained the intention of the issue incorrectly. The goal is not to remove tests at all. The intention of the issue is to move all test from `tests\dppl` to `tests` and update other files accordingly (i.e. https://github.com/IntelPython/numba-dppy/blob/49a172dd908856c0bebc1017b1cf02eafb1004a6/numba_dppy/tests/__init__.py#L14).

**Closed** 2020-12-05 01:08 UTC
Labels: good first issue
